// Code generated by scripts/arithd.goal. DO NOT EDIT.

package goal

import (
	"math"
	"strings"
)

// equal returns x=y.
func equal(x, y V) V {
	if x.IsI() {
		return equalIV(x.I(), y)
	}
	if x.IsF() {
		return equalFV(x.F(), y)
	}
	switch xv := x.value.(type) {
	case S:
		return equalSV(xv, y)
	case *AB:
		return equalABV(xv, y)
	case *AF:
		return equalAFV(xv, y)
	case *AI:
		return equalAIV(xv, y)
	case *AS:
		return equalASV(xv, y)
	case *AV:
		switch yv := y.value.(type) {
		case *Dict:
			return newDictValues(yv.keys, equal(x, NewV(yv.values)))
		case array:
			if yv.Len() != xv.Len() {
				return panicLength("x=y", xv.Len(), yv.Len())
			}
			return dyadAVarray(xv, yv, equal)
		}
		return dyadAVV(xv, y, equal)
	case *Dict:
		yv, ok := y.value.(*Dict)
		if ok {
			r := dictArith(xv, yv, equal)
			if r.IsPanic() {
				return ppanic("d=d", r)
			}
			return r
		}
		return newDictValues(xv.keys, equal(NewV(xv.values), y))
	default:
		return panicType("x=y", "x", x)
	}
}

func equalFV(x float64, y V) V {
	if y.IsI() {
		return NewI(int64(b2B(x == float64(y.I()))))
	}
	if y.IsF() {
		return NewI(int64(b2B(x == y.F())))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := yv.reuse()
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x == float64(yi)))
		}
		return NewV(r)
	case *AF:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x == yi))
		}
		return NewV(r)
	case *AI:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x == float64(yi)))
		}
		return NewV(r)
	case *Dict:
		v := equalFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := equalFV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x=y", "y", y)
	}
}

func equalIV(x int64, y V) V {
	if y.IsI() {
		return NewI(int64(b2B(x == y.I())))
	}
	if y.IsF() {
		return NewI(int64(b2B(float64(x) == y.F())))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := yv.reuse()
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x == int64(yi)))
		}
		return NewV(r)
	case *AF:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(float64(x) == yi))
		}
		return NewV(r)
	case *AI:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x == yi))
		}
		return NewV(r)
	case *Dict:
		v := equalIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := equalIV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x=y", "y", y)
	}
}

func equalSV(x S, y V) V {
	switch yv := y.value.(type) {
	case S:
		return NewI(int64(int64(b2B(S(x) == S(yv)))))
	case *AS:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(S(x) == S(yi)))
		}
		return NewV(r)
	case *Dict:
		v := equalSV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := equalSV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x=y", "y", y)
	}
}

func equalABV(x *AB, y V) V {
	if y.IsI() {
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(int64(xi) == int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) == float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi == yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) == yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(int64(xi) == yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := equalABV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := equalIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x=y", "y", y)
	}
}

func equalAFV(x *AF, y V) V {
	if y.IsI() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi == float64(int64(y.I()))))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi == float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi == float64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi == yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi == float64(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := equalAFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := equalFV(float64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x=y", "y", y)
	}
}

func equalAIV(x *AI, y V) V {
	if y.IsI() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi == int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) == float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi == int64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) == yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi == yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := equalAIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := equalIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x=y", "y", y)
	}
}

func equalASV(x *AS, y V) V {
	switch yv := y.value.(type) {
	case S:
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		for i := range r.elts {
			r.elts[i] = byte(b2B(S(x.At(i)) == S(yv)))
		}
		return NewV(r)
	case *AS:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(S(xi) == S(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := equalASV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x=y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := equalSV(S(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x=y", "y", y)
	}
}

// lesser returns x<y.
func lesser(x, y V) V {
	if x.IsI() {
		return lesserIV(x.I(), y)
	}
	if x.IsF() {
		return lesserFV(x.F(), y)
	}
	switch xv := x.value.(type) {
	case S:
		return lesserSV(xv, y)
	case *AB:
		return lesserABV(xv, y)
	case *AF:
		return lesserAFV(xv, y)
	case *AI:
		return lesserAIV(xv, y)
	case *AS:
		return lesserASV(xv, y)
	case *AV:
		switch yv := y.value.(type) {
		case *Dict:
			return newDictValues(yv.keys, lesser(x, NewV(yv.values)))
		case array:
			if yv.Len() != xv.Len() {
				return panicLength("x<y", xv.Len(), yv.Len())
			}
			return dyadAVarray(xv, yv, lesser)
		}
		return dyadAVV(xv, y, lesser)
	case *Dict:
		yv, ok := y.value.(*Dict)
		if ok {
			r := dictArith(xv, yv, lesser)
			if r.IsPanic() {
				return ppanic("d<d", r)
			}
			return r
		}
		return newDictValues(xv.keys, lesser(NewV(xv.values), y))
	default:
		return panicType("x<y", "x", x)
	}
}

func lesserFV(x float64, y V) V {
	if y.IsI() {
		return NewI(int64(b2B(x < float64(y.I()))))
	}
	if y.IsF() {
		return NewI(int64(b2B(x < y.F())))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := yv.reuse()
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x < float64(yi)))
		}
		return NewV(r)
	case *AF:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x < yi))
		}
		return NewV(r)
	case *AI:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x < float64(yi)))
		}
		return NewV(r)
	case *Dict:
		v := lesserFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := lesserFV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x<y", "y", y)
	}
}

func lesserIV(x int64, y V) V {
	if y.IsI() {
		return NewI(int64(b2B(x < y.I())))
	}
	if y.IsF() {
		return NewI(int64(b2B(float64(x) < y.F())))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := yv.reuse()
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x < int64(yi)))
		}
		return NewV(r)
	case *AF:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(float64(x) < yi))
		}
		return NewV(r)
	case *AI:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x < yi))
		}
		return NewV(r)
	case *Dict:
		v := lesserIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := lesserIV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x<y", "y", y)
	}
}

func lesserSV(x S, y V) V {
	switch yv := y.value.(type) {
	case S:
		return NewI(int64(int64(b2B(S(x) < S(yv)))))
	case *AS:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(S(x) < S(yi)))
		}
		return NewV(r)
	case *Dict:
		v := lesserSV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := lesserSV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x<y", "y", y)
	}
}

func lesserABV(x *AB, y V) V {
	if y.IsI() {
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(int64(xi) < int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) < float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi < yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) < yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(int64(xi) < yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := lesserABV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := lesserIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x<y", "y", y)
	}
}

func lesserAFV(x *AF, y V) V {
	if y.IsI() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi < float64(int64(y.I()))))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi < float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi < float64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi < yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi < float64(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := lesserAFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := lesserFV(float64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x<y", "y", y)
	}
}

func lesserAIV(x *AI, y V) V {
	if y.IsI() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi < int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) < float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi < int64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) < yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi < yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := lesserAIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := lesserIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x<y", "y", y)
	}
}

func lesserASV(x *AS, y V) V {
	switch yv := y.value.(type) {
	case S:
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		for i := range r.elts {
			r.elts[i] = byte(b2B(S(x.At(i)) < S(yv)))
		}
		return NewV(r)
	case *AS:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(S(xi) < S(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := lesserASV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x<y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := lesserSV(S(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x<y", "y", y)
	}
}

// greater returns x>y.
func greater(x, y V) V {
	if x.IsI() {
		return greaterIV(x.I(), y)
	}
	if x.IsF() {
		return greaterFV(x.F(), y)
	}
	switch xv := x.value.(type) {
	case S:
		return greaterSV(xv, y)
	case *AB:
		return greaterABV(xv, y)
	case *AF:
		return greaterAFV(xv, y)
	case *AI:
		return greaterAIV(xv, y)
	case *AS:
		return greaterASV(xv, y)
	case *AV:
		switch yv := y.value.(type) {
		case *Dict:
			return newDictValues(yv.keys, greater(x, NewV(yv.values)))
		case array:
			if yv.Len() != xv.Len() {
				return panicLength("x>y", xv.Len(), yv.Len())
			}
			return dyadAVarray(xv, yv, greater)
		}
		return dyadAVV(xv, y, greater)
	case *Dict:
		yv, ok := y.value.(*Dict)
		if ok {
			r := dictArith(xv, yv, greater)
			if r.IsPanic() {
				return ppanic("d>d", r)
			}
			return r
		}
		return newDictValues(xv.keys, greater(NewV(xv.values), y))
	default:
		return panicType("x>y", "x", x)
	}
}

func greaterFV(x float64, y V) V {
	if y.IsI() {
		return NewI(int64(b2B(x > float64(y.I()))))
	}
	if y.IsF() {
		return NewI(int64(b2B(x > y.F())))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := yv.reuse()
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x > float64(yi)))
		}
		return NewV(r)
	case *AF:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x > yi))
		}
		return NewV(r)
	case *AI:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x > float64(yi)))
		}
		return NewV(r)
	case *Dict:
		v := greaterFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := greaterFV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x>y", "y", y)
	}
}

func greaterIV(x int64, y V) V {
	if y.IsI() {
		return NewI(int64(b2B(x > y.I())))
	}
	if y.IsF() {
		return NewI(int64(b2B(float64(x) > y.F())))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := yv.reuse()
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x > int64(yi)))
		}
		return NewV(r)
	case *AF:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(float64(x) > yi))
		}
		return NewV(r)
	case *AI:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(x > yi))
		}
		return NewV(r)
	case *Dict:
		v := greaterIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := greaterIV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x>y", "y", y)
	}
}

func greaterSV(x S, y V) V {
	switch yv := y.value.(type) {
	case S:
		return NewI(int64(int64(b2B(S(x) > S(yv)))))
	case *AS:
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(yv.rc)}
		r.flags |= flagBool
		for i, yi := range yv.elts {
			r.elts[i] = byte(b2B(S(x) > S(yi)))
		}
		return NewV(r)
	case *Dict:
		v := greaterSV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := greaterSV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x>y", "y", y)
	}
}

func greaterABV(x *AB, y V) V {
	if y.IsI() {
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(int64(xi) > int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) > float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi > yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) > yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := x.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(int64(xi) > yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := greaterABV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := greaterIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x>y", "y", y)
	}
}

func greaterAFV(x *AF, y V) V {
	if y.IsI() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi > float64(int64(y.I()))))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi > float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi > float64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi > yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi > float64(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := greaterAFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := greaterFV(float64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x>y", "y", y)
	}
}

func greaterAIV(x *AI, y V) V {
	if y.IsI() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi > int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) > float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi > int64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(float64(xi) > yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(xi > yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := greaterAIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := greaterIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x>y", "y", y)
	}
}

func greaterASV(x *AS, y V) V {
	switch yv := y.value.(type) {
	case S:
		r := &AB{elts: make([]byte, x.Len()), rc: reuseRCp(x.rc)}
		for i := range r.elts {
			r.elts[i] = byte(b2B(S(x.At(i)) > S(yv)))
		}
		return NewV(r)
	case *AS:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := &AB{elts: make([]byte, yv.Len()), rc: reuseRCp(x.rc)}
		r.flags |= flagBool
		for i, xi := range x.elts {
			r.elts[i] = byte(b2B(S(xi) > S(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := greaterASV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x>y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := greaterSV(S(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x>y", "y", y)
	}
}

// add returns x+y.
func add(x, y V) V {
	if x.IsI() {
		return addIV(x.I(), y)
	}
	if x.IsF() {
		return addFV(x.F(), y)
	}
	switch xv := x.value.(type) {
	case S:
		return addSV(xv, y)
	case *AB:
		return addABV(xv, y)
	case *AF:
		return addAFV(xv, y)
	case *AI:
		return addAIV(xv, y)
	case *AS:
		return addASV(xv, y)
	case *AV:
		switch yv := y.value.(type) {
		case *Dict:
			return newDictValues(yv.keys, add(x, NewV(yv.values)))
		case array:
			if yv.Len() != xv.Len() {
				return panicLength("x+y", xv.Len(), yv.Len())
			}
			return dyadAVarray(xv, yv, add)
		}
		return dyadAVV(xv, y, add)
	case *Dict:
		yv, ok := y.value.(*Dict)
		if ok {
			r := dictArith(xv, yv, add)
			if r.IsPanic() {
				return ppanic("d+d", r)
			}
			return r
		}
		return newDictValues(xv.keys, add(NewV(xv.values), y))
	default:
		return panicType("x+y", "x", x)
	}
}

func addFV(x float64, y V) V {
	if y.IsI() {
		return NewF(x + float64(y.I()))
	}
	if y.IsF() {
		return NewF(x + y.F())
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(x + float64(yi))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(x + yi)
		}
		return NewV(r)
	case *AI:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(x + float64(yi))
		}
		return NewV(r)
	case *Dict:
		v := addFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := addFV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x+y", "y", y)
	}
}

func addIV(x int64, y V) V {
	if y.IsI() {
		return NewI(x + y.I())
	}
	if y.IsF() {
		return NewF(float64(x) + y.F())
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AI{elts: make([]int64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = int64(x + int64(yi))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(float64(x) + yi)
		}
		return NewV(r)
	case *AI:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = int64(x + yi)
		}
		return NewV(r)
	case *Dict:
		v := addIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := addIV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x+y", "y", y)
	}
}

func addSV(x S, y V) V {
	switch yv := y.value.(type) {
	case S:
		return NewV(S(S(x) + S(yv)))
	case *AS:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = string(S(x) + S(yi))
		}
		return NewV(r)
	case *Dict:
		v := addSV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := addSV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x+y", "y", y)
	}
}

func addABV(x *AB, y V) V {
	if y.IsI() {
		r := &AI{elts: make([]int64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = int64(int64(xi) + int64(y.I()))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) + float64(y.F()))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := &AI{elts: make([]int64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = int64(int64(xi) + int64(yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) + yv.At(i))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(int64(xi) + yv.At(i))
		}
		return NewV(r)
	case *Dict:
		v := addABV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := addIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x+y", "y", y)
	}
}

func addAFV(x *AF, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi + float64(int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi + float64(y.F()))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi + float64(yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi + yv.At(i))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi + float64(yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := addAFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := addFV(float64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x+y", "y", y)
	}
}

func addAIV(x *AI, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(xi + int64(y.I()))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) + float64(y.F()))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(xi + int64(yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) + yv.At(i))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(xi + yv.At(i))
		}
		return NewV(r)
	case *Dict:
		v := addAIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := addIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x+y", "y", y)
	}
}

func addASV(x *AS, y V) V {
	switch yv := y.value.(type) {
	case S:
		r := x.reuse()
		for i := range r.elts {
			r.elts[i] = string(S(x.At(i)) + S(yv))
		}
		return NewV(r)
	case *AS:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(S(xi) + S(yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := addASV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x+y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := addSV(S(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x+y", "y", y)
	}
}

// subtract returns x-y.
func subtract(x, y V) V {
	if x.IsI() {
		return subtractIV(x.I(), y)
	}
	if x.IsF() {
		return subtractFV(x.F(), y)
	}
	switch xv := x.value.(type) {
	case S:
		return subtractSV(xv, y)
	case *AB:
		return subtractABV(xv, y)
	case *AF:
		return subtractAFV(xv, y)
	case *AI:
		return subtractAIV(xv, y)
	case *AS:
		return subtractASV(xv, y)
	case *AV:
		switch yv := y.value.(type) {
		case *Dict:
			return newDictValues(yv.keys, subtract(x, NewV(yv.values)))
		case array:
			if yv.Len() != xv.Len() {
				return panicLength("x-y", xv.Len(), yv.Len())
			}
			return dyadAVarray(xv, yv, subtract)
		}
		return dyadAVV(xv, y, subtract)
	case *Dict:
		yv, ok := y.value.(*Dict)
		if ok {
			r := dictArith(xv, yv, subtract)
			if r.IsPanic() {
				return ppanic("d-d", r)
			}
			return r
		}
		return newDictValues(xv.keys, subtract(NewV(xv.values), y))
	default:
		return panicType("x-y", "x", x)
	}
}

func subtractFV(x float64, y V) V {
	if y.IsI() {
		return NewF(x - float64(y.I()))
	}
	if y.IsF() {
		return NewF(x - y.F())
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(x - float64(yi))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(x - yi)
		}
		return NewV(r)
	case *AI:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(x - float64(yi))
		}
		return NewV(r)
	case *Dict:
		v := subtractFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := subtractFV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x-y", "y", y)
	}
}

func subtractIV(x int64, y V) V {
	if y.IsI() {
		return NewI(x - y.I())
	}
	if y.IsF() {
		return NewF(float64(x) - y.F())
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AI{elts: make([]int64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = int64(x - int64(yi))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(float64(x) - yi)
		}
		return NewV(r)
	case *AI:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = int64(x - yi)
		}
		return NewV(r)
	case *Dict:
		v := subtractIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := subtractIV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x-y", "y", y)
	}
}

func subtractSV(x S, y V) V {
	switch yv := y.value.(type) {
	case S:
		return NewV(S(strings.TrimSuffix(string(S(x)), string(S(yv)))))
	case *AS:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = string(strings.TrimSuffix(string(S(x)), string(S(yi))))
		}
		return NewV(r)
	case *Dict:
		v := subtractSV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := subtractSV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x-y", "y", y)
	}
}

func subtractABV(x *AB, y V) V {
	if y.IsI() {
		r := &AI{elts: make([]int64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = int64(int64(xi) - int64(y.I()))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) - float64(y.F()))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := &AI{elts: make([]int64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = int64(int64(xi) - int64(yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) - yv.At(i))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(int64(xi) - yv.At(i))
		}
		return NewV(r)
	case *Dict:
		v := subtractABV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := subtractIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x-y", "y", y)
	}
}

func subtractAFV(x *AF, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi - float64(int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi - float64(y.F()))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi - float64(yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi - yv.At(i))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi - float64(yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := subtractAFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := subtractFV(float64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x-y", "y", y)
	}
}

func subtractAIV(x *AI, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(xi - int64(y.I()))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) - float64(y.F()))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(xi - int64(yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) - yv.At(i))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(xi - yv.At(i))
		}
		return NewV(r)
	case *Dict:
		v := subtractAIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := subtractIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x-y", "y", y)
	}
}

func subtractASV(x *AS, y V) V {
	switch yv := y.value.(type) {
	case S:
		r := x.reuse()
		for i := range r.elts {
			r.elts[i] = string(strings.TrimSuffix(string(S(x.At(i))), string(S(yv))))
		}
		return NewV(r)
	case *AS:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(strings.TrimSuffix(string(S(xi)), string(S(yv.At(i)))))
		}
		return NewV(r)
	case *Dict:
		v := subtractASV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x-y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := subtractSV(S(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x-y", "y", y)
	}
}

// multiply returns x*y.
func multiply(x, y V) V {
	if x.IsI() {
		return multiplyIV(x.I(), y)
	}
	if x.IsF() {
		return multiplyFV(x.F(), y)
	}
	switch xv := x.value.(type) {
	case S:
		return multiplySV(xv, y)
	case *AB:
		return multiplyABV(xv, y)
	case *AF:
		return multiplyAFV(xv, y)
	case *AI:
		return multiplyAIV(xv, y)
	case *AS:
		return multiplyASV(xv, y)
	case *AV:
		switch yv := y.value.(type) {
		case *Dict:
			return newDictValues(yv.keys, multiply(x, NewV(yv.values)))
		case array:
			if yv.Len() != xv.Len() {
				return panicLength("x*y", xv.Len(), yv.Len())
			}
			return dyadAVarray(xv, yv, multiply)
		}
		return dyadAVV(xv, y, multiply)
	case *Dict:
		yv, ok := y.value.(*Dict)
		if ok {
			r := dictArith(xv, yv, multiply)
			if r.IsPanic() {
				return ppanic("d*d", r)
			}
			return r
		}
		return newDictValues(xv.keys, multiply(NewV(xv.values), y))
	default:
		return panicType("x*y", "x", x)
	}
}

func multiplyFV(x float64, y V) V {
	if y.IsI() {
		return NewF(x * float64(y.I()))
	}
	if y.IsF() {
		return NewF(x * y.F())
	}
	switch yv := y.value.(type) {
	case S:
		return NewV(S(srepeat(S(yv), int64(x))))
	case *AB:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(x * float64(yi))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(x * yi)
		}
		return NewV(r)
	case *AI:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(x * float64(yi))
		}
		return NewV(r)
	case *AS:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = string(srepeat(S(yi), int64(x)))
		}
		return NewV(r)
	case *Dict:
		v := multiplyFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := multiplyFV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x*y", "y", y)
	}
}

func multiplyIV(x int64, y V) V {
	if y.IsI() {
		return NewI(x * y.I())
	}
	if y.IsF() {
		return NewF(float64(x) * y.F())
	}
	switch yv := y.value.(type) {
	case S:
		return NewV(S(srepeat(S(yv), x)))
	case *AB:
		r := &AI{elts: make([]int64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = int64(x * int64(yi))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(float64(x) * yi)
		}
		return NewV(r)
	case *AI:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = int64(x * yi)
		}
		return NewV(r)
	case *AS:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = string(srepeat(S(yi), x))
		}
		return NewV(r)
	case *Dict:
		v := multiplyIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := multiplyIV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x*y", "y", y)
	}
}

func multiplySV(x S, y V) V {
	if y.IsI() {
		return NewV(S(srepeat(x, y.I())))
	}
	if y.IsF() {
		return NewV(S(srepeat(x, int64(y.F()))))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AS{elts: make([]string, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = string(srepeat(S(x), int64(yi)))
		}
		return NewV(r)
	case *AF:
		r := &AS{elts: make([]string, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = string(srepeat(S(x), int64(yi)))
		}
		return NewV(r)
	case *AI:
		r := &AS{elts: make([]string, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = string(srepeat(S(x), yi))
		}
		return NewV(r)
	case *Dict:
		v := multiplySV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := multiplySV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x*y", "y", y)
	}
}

func multiplyABV(x *AB, y V) V {
	if y.IsI() {
		r := &AI{elts: make([]int64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = int64(int64(xi) * int64(y.I()))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) * float64(y.F()))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case S:
		r := &AS{elts: make([]string, x.Len()), rc: reuseRCp(x.rc)}
		for i := range r.elts {
			r.elts[i] = string(srepeat(S(yv), int64(x.At(i))))
		}
		return NewV(r)
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := &AI{elts: make([]int64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = int64(int64(xi) * int64(yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) * yv.At(i))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(int64(xi) * yv.At(i))
		}
		return NewV(r)
	case *AS:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(srepeat(S(yv.At(i)), int64(xi)))
		}
		return NewV(r)
	case *Dict:
		v := multiplyABV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := multiplyIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x*y", "y", y)
	}
}

func multiplyAFV(x *AF, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi * float64(int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi * float64(y.F()))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case S:
		r := &AS{elts: make([]string, x.Len()), rc: reuseRCp(x.rc)}
		for i := range r.elts {
			r.elts[i] = string(srepeat(S(yv), int64(x.At(i))))
		}
		return NewV(r)
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi * float64(yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi * yv.At(i))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(xi * float64(yv.At(i)))
		}
		return NewV(r)
	case *AS:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(srepeat(S(yv.At(i)), int64(xi)))
		}
		return NewV(r)
	case *Dict:
		v := multiplyAFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := multiplyFV(float64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x*y", "y", y)
	}
}

func multiplyAIV(x *AI, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(xi * int64(y.I()))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) * float64(y.F()))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case S:
		r := &AS{elts: make([]string, x.Len()), rc: reuseRCp(x.rc)}
		for i := range r.elts {
			r.elts[i] = string(srepeat(S(yv), x.At(i)))
		}
		return NewV(r)
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(xi * int64(yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(float64(xi) * yv.At(i))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(xi * yv.At(i))
		}
		return NewV(r)
	case *AS:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(srepeat(S(yv.At(i)), xi))
		}
		return NewV(r)
	case *Dict:
		v := multiplyAIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := multiplyIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x*y", "y", y)
	}
}

func multiplyASV(x *AS, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(srepeat(S(xi), int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(srepeat(S(xi), int64(float64(y.F()))))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(srepeat(S(xi), int64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(srepeat(S(xi), int64(yv.At(i))))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(srepeat(S(xi), yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := multiplyASV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x*y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := multiplySV(S(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x*y", "y", y)
	}
}

// divide returns x%y.
func divide(x, y V) V {
	if x.IsI() {
		return divideIV(x.I(), y)
	}
	if x.IsF() {
		return divideFV(x.F(), y)
	}
	switch xv := x.value.(type) {
	case *AB:
		return divideABV(xv, y)
	case *AF:
		return divideAFV(xv, y)
	case *AI:
		return divideAIV(xv, y)
	case *AV:
		switch yv := y.value.(type) {
		case *Dict:
			return newDictValues(yv.keys, divide(x, NewV(yv.values)))
		case array:
			if yv.Len() != xv.Len() {
				return panicLength("x%y", xv.Len(), yv.Len())
			}
			return dyadAVarray(xv, yv, divide)
		}
		return dyadAVV(xv, y, divide)
	case *Dict:
		yv, ok := y.value.(*Dict)
		if ok {
			r := dictArith(xv, yv, divide)
			if r.IsPanic() {
				return ppanic("d%d", r)
			}
			return r
		}
		return newDictValues(xv.keys, divide(NewV(xv.values), y))
	default:
		return panicType("x%y", "x", x)
	}
}

func divideFV(x float64, y V) V {
	if y.IsI() {
		return NewF(divideF(x, float64(y.I())))
	}
	if y.IsF() {
		return NewF(divideF(x, y.F()))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(divideF(x, float64(yi)))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(divideF(x, yi))
		}
		return NewV(r)
	case *AI:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(divideF(x, float64(yi)))
		}
		return NewV(r)
	case *Dict:
		v := divideFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := divideFV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x%y", "y", y)
	}
}

func divideIV(x int64, y V) V {
	if y.IsI() {
		return NewF(divideF(float64(x), float64(y.I())))
	}
	if y.IsF() {
		return NewF(divideF(float64(x), y.F()))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(divideF(float64(x), float64(yi)))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(divideF(float64(x), yi))
		}
		return NewV(r)
	case *AI:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(divideF(float64(x), float64(yi)))
		}
		return NewV(r)
	case *Dict:
		v := divideIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := divideIV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x%y", "y", y)
	}
}

func divideABV(x *AB, y V) V {
	if y.IsI() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(float64(xi), float64(int64(y.I()))))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(float64(xi), float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(float64(xi), float64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(float64(xi), yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(float64(xi), float64(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := divideABV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := divideIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x%y", "y", y)
	}
}

func divideAFV(x *AF, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(xi, float64(int64(y.I()))))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(xi, float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(xi, float64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(xi, yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(xi, float64(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := divideAFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := divideFV(float64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x%y", "y", y)
	}
}

func divideAIV(x *AI, y V) V {
	if y.IsI() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(float64(xi), float64(int64(y.I()))))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(float64(xi), float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(float64(xi), float64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(float64(xi), yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(divideF(float64(xi), float64(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := divideAIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x%y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := divideIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x%y", "y", y)
	}
}

// minimum returns x&y.
func minimum(x, y V) V {
	if x.IsI() {
		return minimumIV(x.I(), y)
	}
	if x.IsF() {
		return minimumFV(x.F(), y)
	}
	switch xv := x.value.(type) {
	case S:
		return minimumSV(xv, y)
	case *AB:
		return minimumABV(xv, y)
	case *AF:
		return minimumAFV(xv, y)
	case *AI:
		return minimumAIV(xv, y)
	case *AS:
		return minimumASV(xv, y)
	case *AV:
		switch yv := y.value.(type) {
		case *Dict:
			return newDictValues(yv.keys, minimum(x, NewV(yv.values)))
		case array:
			if yv.Len() != xv.Len() {
				return panicLength("x&y", xv.Len(), yv.Len())
			}
			return dyadAVarray(xv, yv, minimum)
		}
		return dyadAVV(xv, y, minimum)
	case *Dict:
		yv, ok := y.value.(*Dict)
		if ok {
			r := dictArith(xv, yv, minimum)
			if r.IsPanic() {
				return ppanic("d&d", r)
			}
			return r
		}
		return newDictValues(xv.keys, minimum(NewV(xv.values), y))
	default:
		return panicType("x&y", "x", x)
	}
}

func minimumFV(x float64, y V) V {
	if y.IsI() {
		return NewF(math.Min(x, float64(y.I())))
	}
	if y.IsF() {
		return NewF(math.Min(x, float64(y.F())))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Min(x, float64(yi)))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Min(x, float64(yi)))
		}
		return NewV(r)
	case *AI:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Min(x, float64(yi)))
		}
		return NewV(r)
	case *Dict:
		v := minimumFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := minimumFV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x&y", "y", y)
	}
}

func minimumIV(x int64, y V) V {
	if y.IsI() {
		return NewI(minI(x, y.I()))
	}
	if y.IsF() {
		return NewF(math.Min(float64(x), y.F()))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AI{elts: make([]int64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = int64(minI(x, int64(yi)))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Min(float64(x), yi))
		}
		return NewV(r)
	case *AI:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = int64(minI(x, yi))
		}
		return NewV(r)
	case *Dict:
		v := minimumIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := minimumIV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x&y", "y", y)
	}
}

func minimumSV(x S, y V) V {
	switch yv := y.value.(type) {
	case S:
		return NewV(S(minS(S(x), S(yv))))
	case *AS:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = string(minS(S(x), S(yi)))
		}
		return NewV(r)
	case *Dict:
		v := minimumSV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := minimumSV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x&y", "y", y)
	}
}

func minimumABV(x *AB, y V) V {
	if y.IsI() {
		r := &AI{elts: make([]int64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = int64(minI(int64(xi), int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Min(float64(xi), float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		b := x.IsBoolean() && yv.IsBoolean()
		r := x.reuse()
		if b {
			for i, xi := range x.elts {
				r.elts[i] = xi & yv.At(i)
			}
			r.flags |= flagBool
			return NewV(r)
		}
		for i, xi := range x.elts {
			r.elts[i] = byte(minB(xi, yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Min(float64(xi), yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(minI(int64(xi), yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := minimumABV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := minimumIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x&y", "y", y)
	}
}

func minimumAFV(x *AF, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Min(xi, float64(int64(y.I()))))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Min(xi, float64(float64(y.F()))))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Min(xi, float64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Min(xi, float64(yv.At(i))))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Min(xi, float64(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := minimumAFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := minimumFV(float64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x&y", "y", y)
	}
}

func minimumAIV(x *AI, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(minI(xi, int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Min(float64(xi), float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(minI(xi, int64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Min(float64(xi), yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(minI(xi, yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := minimumAIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := minimumIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x&y", "y", y)
	}
}

func minimumASV(x *AS, y V) V {
	switch yv := y.value.(type) {
	case S:
		r := x.reuse()
		for i := range r.elts {
			r.elts[i] = string(minS(S(x.At(i)), S(yv)))
		}
		return NewV(r)
	case *AS:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(minS(S(xi), S(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := minimumASV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x&y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := minimumSV(S(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x&y", "y", y)
	}
}

// maximum returns x|y.
func maximum(x, y V) V {
	if x.IsI() {
		return maximumIV(x.I(), y)
	}
	if x.IsF() {
		return maximumFV(x.F(), y)
	}
	switch xv := x.value.(type) {
	case S:
		return maximumSV(xv, y)
	case *AB:
		return maximumABV(xv, y)
	case *AF:
		return maximumAFV(xv, y)
	case *AI:
		return maximumAIV(xv, y)
	case *AS:
		return maximumASV(xv, y)
	case *AV:
		switch yv := y.value.(type) {
		case *Dict:
			return newDictValues(yv.keys, maximum(x, NewV(yv.values)))
		case array:
			if yv.Len() != xv.Len() {
				return panicLength("x|y", xv.Len(), yv.Len())
			}
			return dyadAVarray(xv, yv, maximum)
		}
		return dyadAVV(xv, y, maximum)
	case *Dict:
		yv, ok := y.value.(*Dict)
		if ok {
			r := dictArith(xv, yv, maximum)
			if r.IsPanic() {
				return ppanic("d|d", r)
			}
			return r
		}
		return newDictValues(xv.keys, maximum(NewV(xv.values), y))
	default:
		return panicType("x|y", "x", x)
	}
}

func maximumFV(x float64, y V) V {
	if y.IsI() {
		return NewF(math.Max(x, float64(y.I())))
	}
	if y.IsF() {
		return NewF(math.Max(x, float64(y.F())))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Max(x, float64(yi)))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Max(x, float64(yi)))
		}
		return NewV(r)
	case *AI:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Max(x, float64(yi)))
		}
		return NewV(r)
	case *Dict:
		v := maximumFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := maximumFV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x|y", "y", y)
	}
}

func maximumIV(x int64, y V) V {
	if y.IsI() {
		return NewI(maxI(x, y.I()))
	}
	if y.IsF() {
		return NewF(math.Max(float64(x), y.F()))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AI{elts: make([]int64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = int64(maxI(x, int64(yi)))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Max(float64(x), yi))
		}
		return NewV(r)
	case *AI:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = int64(maxI(x, yi))
		}
		return NewV(r)
	case *Dict:
		v := maximumIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := maximumIV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x|y", "y", y)
	}
}

func maximumSV(x S, y V) V {
	switch yv := y.value.(type) {
	case S:
		return NewV(S(maxS(S(x), S(yv))))
	case *AS:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = string(maxS(S(x), S(yi)))
		}
		return NewV(r)
	case *Dict:
		v := maximumSV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := maximumSV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x|y", "y", y)
	}
}

func maximumABV(x *AB, y V) V {
	if y.IsI() {
		r := &AI{elts: make([]int64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = int64(maxI(int64(xi), int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Max(float64(xi), float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		b := x.IsBoolean() && yv.IsBoolean()
		r := x.reuse()
		if b {
			for i, xi := range x.elts {
				r.elts[i] = xi | yv.At(i)
			}
			r.flags |= flagBool
			return NewV(r)
		}
		for i, xi := range x.elts {
			r.elts[i] = byte(maxB(xi, yv.At(i)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Max(float64(xi), yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(maxI(int64(xi), yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := maximumABV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := maximumIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x|y", "y", y)
	}
}

func maximumAFV(x *AF, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Max(xi, float64(int64(y.I()))))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Max(xi, float64(float64(y.F()))))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Max(xi, float64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Max(xi, float64(yv.At(i))))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Max(xi, float64(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := maximumAFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := maximumFV(float64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x|y", "y", y)
	}
}

func maximumAIV(x *AI, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(maxI(xi, int64(y.I())))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Max(float64(xi), float64(y.F())))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(maxI(xi, int64(yv.At(i))))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Max(float64(xi), yv.At(i)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = int64(maxI(xi, yv.At(i)))
		}
		return NewV(r)
	case *Dict:
		v := maximumAIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := maximumIV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x|y", "y", y)
	}
}

func maximumASV(x *AS, y V) V {
	switch yv := y.value.(type) {
	case S:
		r := x.reuse()
		for i := range r.elts {
			r.elts[i] = string(maxS(S(x.At(i)), S(yv)))
		}
		return NewV(r)
	case *AS:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = string(maxS(S(xi), S(yv.At(i))))
		}
		return NewV(r)
	case *Dict:
		v := maximumASV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x|y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := maximumSV(S(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x|y", "y", y)
	}
}

// arctan2 returns x atan y.
func arctan2(x, y V) V {
	if x.IsI() {
		return arctan2IV(x.I(), y)
	}
	if x.IsF() {
		return arctan2FV(x.F(), y)
	}
	switch xv := x.value.(type) {
	case *AB:
		return arctan2ABV(xv, y)
	case *AF:
		return arctan2AFV(xv, y)
	case *AI:
		return arctan2AIV(xv, y)
	case *AV:
		switch yv := y.value.(type) {
		case *Dict:
			return newDictValues(yv.keys, arctan2(x, NewV(yv.values)))
		case array:
			if yv.Len() != xv.Len() {
				return panicLength("x atan y", xv.Len(), yv.Len())
			}
			return dyadAVarray(xv, yv, arctan2)
		}
		return dyadAVV(xv, y, arctan2)
	case *Dict:
		yv, ok := y.value.(*Dict)
		if ok {
			r := dictArith(xv, yv, arctan2)
			if r.IsPanic() {
				return ppanic("d atan d", r)
			}
			return r
		}
		return newDictValues(xv.keys, arctan2(NewV(xv.values), y))
	default:
		return panicType("x atan y", "x", x)
	}
}

func arctan2FV(x float64, y V) V {
	if y.IsI() {
		return NewF(math.Atan2(float64(y.I()), x))
	}
	if y.IsF() {
		return NewF(math.Atan2(y.F(), x))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Atan2(float64(yi), x))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Atan2(yi, x))
		}
		return NewV(r)
	case *AI:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Atan2(float64(yi), x))
		}
		return NewV(r)
	case *Dict:
		v := arctan2FV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := arctan2FV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x atan y", "y", y)
	}
}

func arctan2IV(x int64, y V) V {
	if y.IsI() {
		return NewF(math.Atan2(float64(y.I()), float64(x)))
	}
	if y.IsF() {
		return NewF(math.Atan2(y.F(), float64(x)))
	}
	switch yv := y.value.(type) {
	case *AB:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Atan2(float64(yi), float64(x)))
		}
		return NewV(r)
	case *AF:
		r := yv.reuse()
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Atan2(yi, float64(x)))
		}
		return NewV(r)
	case *AI:
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(yv.rc)}
		for i, yi := range yv.elts {
			r.elts[i] = float64(math.Atan2(float64(yi), float64(x)))
		}
		return NewV(r)
	case *Dict:
		v := arctan2IV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		r := yv.reuse()
		for i, yi := range yv.elts {
			ri := arctan2IV(x, yi)
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x atan y", "y", y)
	}
}

func arctan2ABV(x *AB, y V) V {
	if y.IsI() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(int64(y.I())), float64(xi)))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(y.F()), float64(xi)))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(yv.At(i)), float64(xi)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(yv.At(i), float64(xi)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(yv.At(i)), float64(xi)))
		}
		return NewV(r)
	case *Dict:
		v := arctan2ABV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := arctan2IV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x atan y", "y", y)
	}
}

func arctan2AFV(x *AF, y V) V {
	if y.IsI() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(int64(y.I())), xi))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(y.F()), xi))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(yv.At(i)), xi))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(yv.At(i), xi))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := x.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(yv.At(i)), xi))
		}
		return NewV(r)
	case *Dict:
		v := arctan2AFV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := arctan2FV(float64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x atan y", "y", y)
	}
}

func arctan2AIV(x *AI, y V) V {
	if y.IsI() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(int64(y.I())), float64(xi)))
		}
		return NewV(r)
	}
	if y.IsF() {
		r := &AF{elts: make([]float64, x.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(y.F()), float64(xi)))
		}
		return NewV(r)
	}
	switch yv := y.value.(type) {
	case *AB:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(yv.At(i)), float64(xi)))
		}
		return NewV(r)
	case *AF:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(yv.At(i), float64(xi)))
		}
		return NewV(r)
	case *AI:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := &AF{elts: make([]float64, yv.Len()), rc: reuseRCp(x.rc)}
		for i, xi := range x.elts {
			r.elts[i] = float64(math.Atan2(float64(yv.At(i)), float64(xi)))
		}
		return NewV(r)
	case *Dict:
		v := arctan2AIV(x, NewV(yv.values))
		if v.IsPanic() {
			return v
		}
		v.InitRC()
		return NewV(&Dict{keys: yv.keys, values: v.value.(array)})
	case *AV:
		if x.Len() != yv.Len() {
			return panicLength("x atan y", x.Len(), yv.Len())
		}
		r := yv.reuse()
		for i := range r.elts {
			ri := arctan2IV(int64(x.At(i)), yv.At(i))
			if ri.IsPanic() {
				return ri
			}
			r.elts[i] = ri
		}
		return NewV(r)
	default:
		return panicType("x atan y", "y", y)
	}
}
