// Code generated by "stringer -type=TokenType,astTokenType,opcode -output stringer.go"; DO NOT EDIT.

package goal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[EOF-1]
	_ = x[ERROR-2]
	_ = x[ADVERB-3]
	_ = x[DYAD-4]
	_ = x[DYADASSIGN-5]
	_ = x[IDENT-6]
	_ = x[LEFTBRACE-7]
	_ = x[LEFTBRACKET-8]
	_ = x[LEFTPAREN-9]
	_ = x[NEWLINE-10]
	_ = x[NUMBER-11]
	_ = x[MONAD-12]
	_ = x[REGEXP-13]
	_ = x[RIGHTBRACE-14]
	_ = x[RIGHTBRACKET-15]
	_ = x[RIGHTPAREN-16]
	_ = x[SEMICOLON-17]
	_ = x[STRING-18]
}

const _TokenType_name = "NONEEOFERRORADVERBDYADDYADASSIGNIDENTLEFTBRACELEFTBRACKETLEFTPARENNEWLINENUMBERMONADREGEXPRIGHTBRACERIGHTBRACKETRIGHTPARENSEMICOLONSTRING"

var _TokenType_index = [...]uint8{0, 4, 7, 12, 18, 22, 32, 37, 46, 57, 66, 73, 79, 84, 90, 100, 112, 122, 131, 137}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[astNUMBER-0]
	_ = x[astSTRING-1]
	_ = x[astIDENT-2]
	_ = x[astMONAD-3]
	_ = x[astDYAD-4]
	_ = x[astADVERB-5]
	_ = x[astREGEXP-6]
	_ = x[astEMPTYLIST-7]
}

const _astTokenType_name = "astNUMBERastSTRINGastIDENTastMONADastDYADastADVERBastREGEXPastEMPTYLIST"

var _astTokenType_index = [...]uint8{0, 9, 18, 26, 34, 41, 50, 59, 71}

func (i astTokenType) String() string {
	if i < 0 || i >= astTokenType(len(_astTokenType_index)-1) {
		return "astTokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _astTokenType_name[_astTokenType_index[i]:_astTokenType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opNop-0]
	_ = x[opNil-1]
	_ = x[opConst-2]
	_ = x[opInt-3]
	_ = x[opVariadic-4]
	_ = x[opLambda-5]
	_ = x[opLocal-6]
	_ = x[opLocalLast-7]
	_ = x[opGlobal-8]
	_ = x[opGlobalLast-9]
	_ = x[opAssignGlobal-10]
	_ = x[opAssignLocal-11]
	_ = x[opApply-12]
	_ = x[opApplyV-13]
	_ = x[opApplyGlobal-14]
	_ = x[opDerive-15]
	_ = x[opApply2-16]
	_ = x[opApply2V-17]
	_ = x[opApplyN-18]
	_ = x[opApplyNGlobal-19]
	_ = x[opApplyNV-20]
	_ = x[opDrop-21]
	_ = x[opJump-22]
	_ = x[opJumpFalse-23]
	_ = x[opJumpTrue-24]
	_ = x[opReturn-25]
	_ = x[opTry-26]
}

const _opcode_name = "opNopopNilopConstopIntopVariadicopLambdaopLocalopLocalLastopGlobalopGlobalLastopAssignGlobalopAssignLocalopApplyopApplyVopApplyGlobalopDeriveopApply2opApply2VopApplyNopApplyNGlobalopApplyNVopDropopJumpopJumpFalseopJumpTrueopReturnopTry"

var _opcode_index = [...]uint8{0, 5, 10, 17, 22, 32, 40, 47, 58, 66, 78, 92, 105, 112, 120, 133, 141, 149, 158, 166, 180, 189, 195, 201, 212, 222, 230, 235}

func (i opcode) String() string {
	if i < 0 || i >= opcode(len(_opcode_index)-1) {
		return "opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opcode_name[_opcode_index[i]:_opcode_index[i+1]]
}
